### ISSUE TITLE
Error when call `onesky.locales()`

### ISSUE THREAD

**Issue by voznik** [SpeCT/gulp-onesky#1]
when I try to get separate translations  files as in your 2nd example

``` javascript
'use strict';
// gulp
var gulp = require('gulp');
var onesky = require('gulp-onesky');
var oneskyOptions = {
  publicKey: 'myKey',
  secretKey: 'myKey',
  projectId: '184430',
  sourceFile: 'translation_en.json'
};
gulp.task('translate', function () {
  onesky(oneskyOptions)
  .pipe(gulp.dest('app/i18n'));
});


gulp.task('translate-more', function () {
  onesky.locales(oneskyOptions)
  .pipe(gulp.dest('app/i18n'));
});
```

 I get Error:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at /home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/index.js:39:22
    at Array.forEach (native)
    at /home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/index.js:37:25
    at Request._callback (/home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/index.js:77:5)
    at Request.self.callback (/home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/node_modules/request/request.js:1048:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/voznik/workspace/crumzi-mobile/node_modules/gulp-onesky/node_modules/request/request.js:969:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
```

**Comment by faustlifes** [comment]
I got this error too!

**Comment by Tusko** [comment]
+++
